---
title: "Appendix 2: Prior distributions and multinomial-Dirichlet mixture"
output: pdf_document
---

## Appendix 2.1

The following vague prior distributions were used in the model. Parameter descriptions associated with parameter symbols can be found in Table 1 of the main text:

Trap size selectivity parameters:

$$
h_M^{max} \sim Uniform(0, 0.1)
$$

$$
h_M^A \sim Uniform(35, 60)
$$

$$
h_M^{\sigma} \sim Uniform(3, 10)
$$

$$
h_F^{max} \sim Uniform(0, 0.1)
$$

$$
h_F^k \sim Uniform(0.1, 1.5)
$$

$$
h_F^0 \sim Uniform(30, 100)
$$

$$
h_S^{max} \sim Uniform(0, 0.1)
$$

$$
h_S^k \sim Uniform(0.1, 1.5)
$$

$$
h_S^0 \sim Uniform(30, 100)
$$


Natural mortality parameters:

$$
\beta_{\alpha} \sim Uniform(0, 50)
$$

$$
\beta_{\theta} \sim Uniform(0, 150)
$$

$$
\alpha \sim Uniform(0, 10000)
$$


Overwinter mortality parameters:

$$
\alpha^o_{\alpha} \sim Uniform(0, 50)
$$

$$
\alpha^o_{\theta} \sim Uniform(0, 150)
$$


Seasonal growth parameters:

$$
\sigma^G \sim Uniform(0.01, 4)
$$


Overdispersion observation process (see Appendix 2.2):

$$
\rho \sim Beta(1, 1)
$$


Initial population density and annual recruitment:


$$
\mu^A \sim Uniform(3.25, 4.5)
$$

$$
\sigma^A \sim Uniform(0.1, 1)
$$

$$
\mu^R \sim Uniform(1, 25)
$$

$$
\sigma^R \sim Uniform(0.01, 20)
$$

$$
\mu^{\lambda} \sim Uniform(1, 1000000)
$$

$$
\sigma^{\lambda} \sim Uniform(0, 10000)
$$

$$
\lambda^A \sim Uniform(1, 1000000)
$$




Since the model was estimated hierarchically, with the seasonal growth model was estimated first with the size-at-age data (D2), and the marginal posterior distributions from this first model were used in the second model with the time series data (D1) and mark-recapture data (D3). Informative priors used in the second model for parameters $A$, $k$, $x_[\infty]$, and $t_s$ can be found in Table A1.2 in Appendix 1.2.4.

## Appendix 2.2

Similarly to how a beta-binomial replaces a single probability with a Beta distribution of probabilities among binomial draws to account for overdispersion, the Dirichlet-multinomial mixture replaces a single vector of probabilities (that sum to one) with a Dirichlet distribution of such vectors to account for overdispersion in counts among traps.

The parameter $\alpha^D$ described in the main text governs the amount of overdispersion in the Dirichlet-multinomial mixture distribution and generates the conditional probability of capture, $p^C(x)_{t,j,y}$, across individual traps.

The parameter $\alpha^D$ is linked to the sampled parameter, $\rho$:

$$
\alpha^D = p^C(x)_{t,j,y} \times p^D
$$

$$
p^D = \frac{1-\rho}{\rho}
$$

